package Vista;

import Controlador.ControladorView;
import Controlador.ControladorClientes;
import Controlador.ControladorProductos;
import Controlador.ControladorVentas;
import Modelo.Cliente;
import Modelo.Venta;
import javax.swing.JOptionPane;

/**
 *
 * @author naoal
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDPEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MBUsuarios = new javax.swing.JMenu();
        RegistroNuevoCliente = new javax.swing.JMenuItem();
        MIEditarUsuario = new javax.swing.JMenuItem();
        MostrarInfoClientes = new javax.swing.JMenuItem();
        EliminarCliente = new javax.swing.JMenuItem();
        JBProductos = new javax.swing.JMenu();
        JMIMostrarProductos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        EliminarVenta = new javax.swing.JMenu();
        crearVentaBoton = new javax.swing.JMenuItem();
        verVentaBoton = new javax.swing.JMenuItem();
        eliminarVentaBoton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDPEscritorioLayout = new javax.swing.GroupLayout(JDPEscritorio);
        JDPEscritorio.setLayout(JDPEscritorioLayout);
        JDPEscritorioLayout.setHorizontalGroup(
            JDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        JDPEscritorioLayout.setVerticalGroup(
            JDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        MBUsuarios.setText("Clientes");

        RegistroNuevoCliente.setText("Registrar nuevo cliente");
        RegistroNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroNuevoClienteActionPerformed(evt);
            }
        });
        MBUsuarios.add(RegistroNuevoCliente);

        MIEditarUsuario.setText("Editar información de Cliente");
        MIEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIEditarUsuarioActionPerformed(evt);
            }
        });
        MBUsuarios.add(MIEditarUsuario);

        MostrarInfoClientes.setText("Mostrar información clientes");
        MostrarInfoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarInfoClientesActionPerformed(evt);
            }
        });
        MBUsuarios.add(MostrarInfoClientes);

        EliminarCliente.setText("Eliminar Cliente");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });
        MBUsuarios.add(EliminarCliente);

        jMenuBar1.add(MBUsuarios);

        JBProductos.setText("Productos");

        JMIMostrarProductos.setText("Mostrar Productos");
        JMIMostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIMostrarProductosActionPerformed(evt);
            }
        });
        JBProductos.add(JMIMostrarProductos);

        jMenuItem1.setText("Agregar Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JBProductos.add(jMenuItem1);

        jMenuItem2.setText("Editar Producto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        JBProductos.add(jMenuItem2);

        jMenuItem3.setText("Eliminar Producto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        JBProductos.add(jMenuItem3);

        jMenuBar1.add(JBProductos);

        EliminarVenta.setText("Ventas");

        crearVentaBoton.setText("Crear venta");
        crearVentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVentaBotonActionPerformed(evt);
            }
        });
        EliminarVenta.add(crearVentaBoton);

        verVentaBoton.setText("Ver ventas");
        verVentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verVentaBotonActionPerformed(evt);
            }
        });
        EliminarVenta.add(verVentaBoton);

        eliminarVentaBoton.setText("Eliminar venta");
        eliminarVentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVentaBotonActionPerformed(evt);
            }
        });
        EliminarVenta.add(eliminarVentaBoton);

        jMenuBar1.add(EliminarVenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroNuevoClienteActionPerformed
        Cliente nuevoCliente = ControladorView.crearClienteView() ;
        ControladorClientes.crearCliente(nuevoCliente);

        //System.out.println("Usuario registrado correctamente");

    }//GEN-LAST:event_RegistroNuevoClienteActionPerformed

    private void JMIMostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIMostrarProductosActionPerformed
        // TODO add your handling code here:
        ControladorProductos gestionProductos = new ControladorProductos();
        gestionProductos.consultarProductosCompletos();

    }//GEN-LAST:event_JMIMostrarProductosActionPerformed


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ControladorProductos gestionProductos = new ControladorProductos();
        gestionProductos.insertarProducto("huevo","002");    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ControladorProductos gestionProductos = new ControladorProductos();
        gestionProductos.actualizarProducto("2","Leche","022");     }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        ControladorProductos gestionProductos = new ControladorProductos();
        gestionProductos.eliminarProducto(6);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MIEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIEditarUsuarioActionPerformed
        // TODO add your handling code here:
        int resultado = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas editar este usuario?", "Editar Usuario", JOptionPane.YES_NO_OPTION);

        // Si el usuario elige "Sí" en el mensaje de confirmación
        if (resultado == JOptionPane.YES_OPTION) {
            // Código para editar el usuario
            // ...
            // Imprimir mensaje de confirmación
            System.out.println("Usuario editado correctamente");
        }

    }//GEN-LAST:event_MIEditarUsuarioActionPerformed

    private void MostrarInfoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarInfoClientesActionPerformed
        ControladorClientes gestionClientes = new ControladorClientes();
        gestionClientes.consultarClientesCompletos();
    }//GEN-LAST:event_MostrarInfoClientesActionPerformed

    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        int eliminarCliente = ControladorView.eliminarCliente();
        ControladorClientes.eliminarCliente(eliminarCliente);
    }//GEN-LAST:event_EliminarClienteActionPerformed

    private void eliminarVentaBotonActionPerformed(java.awt.event.ActionEvent evt) {
        int eliminarVenta = ControladorView.eliminarVentaView();
        ControladorVentas.eliminarVenta(eliminarVenta);
    }

    private void crearVentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVentaBotonActionPerformed
        Venta nuevaVenta = CreacionVentaView.crearVentaView();
        ControladorVentas.insertarVenta(nuevaVenta);

    }//GEN-LAST:event_crearVentaBotonActionPerformed

    private void verVentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verVentaBotonActionPerformed
        ControladorVentas gestionVentas = new ControladorVentas();
        gestionVentas.consultarVentasCompletos();
    }//GEN-LAST:event_verVentaBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EliminarCliente;
    private javax.swing.JMenu EliminarVenta;
    private javax.swing.JMenu JBProductos;
    private javax.swing.JDesktopPane JDPEscritorio;
    private javax.swing.JMenuItem JMIMostrarProductos;
    private javax.swing.JMenu MBUsuarios;
    private javax.swing.JMenuItem MIEditarUsuario;
    private javax.swing.JMenuItem MostrarInfoClientes;
    private javax.swing.JMenuItem RegistroNuevoCliente;
    private javax.swing.JMenuItem crearVentaBoton;
    private javax.swing.JMenuItem eliminarVentaBoton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem verVentaBoton;
    // End of variables declaration//GEN-END:variables
}
