/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.pfcsgrupo2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
//import java.util.ArrayList;

/**
 *
 * @author naoal
 */
public class RegistroUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JTNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTFechaNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTContrasena = new javax.swing.JTextField();
        JBGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAInfoUser = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setText("Nombre completo");

        JTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Teléfono");

        JTTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTTelefonoActionPerformed(evt);
            }
        });

        jLabel4.setText("Correo electrónico");

        JTCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCorreoActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de nacimiento");

        JTFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFechaNacimientoActionPerformed(evt);
            }
        });

        jLabel6.setText("Contraseña");

        JTContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTContrasenaActionPerformed(evt);
            }
        });

        JBGuardar.setText("Guardar");
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        JTAInfoUser.setColumns(20);
        JTAInfoUser.setRows(5);
        jScrollPane1.setViewportView(JTAInfoUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(JTNombre)
                            .addComponent(JTTelefono)
                            .addComponent(JTCorreo)
                            .addComponent(JTFechaNacimiento)
                            .addComponent(JTContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(JBGuardar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(JTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBGuardar)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNombreActionPerformed

    private void JTTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTTelefonoActionPerformed

    private void JTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCorreoActionPerformed

    private void JTFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFechaNacimientoActionPerformed

    private void JTContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTContrasenaActionPerformed
        // TJTIdentificacionr handling code here:
    }//GEN-LAST:event_JTContrasenaActionPerformed

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
        // TODO add your handling code here:
        String nombre = JTNombre.getText();
        String telefono = JTTelefono.getText();
        String correo = JTCorreo.getText();
        String fechaNacimiento = JTFechaNacimiento.getText();
        String contrasena = JTContrasena.getText();
        
        Connection conexion = null;
        PreparedStatement consulta = null;
        try {
            // DATOS DE CONEXION Y LOGGEO
            String url = "jdbc:mysql://127.0.0.1:3306/pfcsgrupo2";
            String username = "root";
            String password = "ElianCortes.21";

            // ESTABLECER CONEXION
            conexion = DriverManager.getConnection(url, username, password);

            // PREPARAR CONSULTA DE INSERCIÓN
            String insertQuery = "INSERT INTO usuarios (nombre, telefono, correo, fechaNacimiento, contraseña) VALUES (?, ?, ?, ?, ?)";
            consulta = conexion.prepareStatement(insertQuery);

            // ESTABLECER LOS VALORES DE LOS PARÁMETROS
            consulta.setString(1, nombre);
            consulta.setString(2, telefono);
            consulta.setString(3, correo);
            consulta.setString(4, fechaNacimiento);
            consulta.setString(5, contrasena);

            // EJECUTAR LA CONSULTA DE INSERCIÓN
            int filasAfectadas = consulta.executeUpdate();

            if (filasAfectadas > 0) {
                System.out.println("Inserción exitosa");
                JTAInfoUser.setText("Usuario agregado con exito!");
            } else {
                System.out.println("La inserción no tuvo éxito");
            }
//            while (resultado.next()) {
//                int id = resultado.getInt("id");
//                String idString = String.valueOf(id);
//                String nombreString = resultado.getString("nombre");
//                String telefonoString = resultado.getString("telefono");
//                String correoString = resultado.getString("correo");
//                String fechaString = resultado.getString("fechaNacimiento");
//
//                
//                    JTAInfoUser.setText("ID; " + idString + "\n"
//                            + "Nombre: " + nombreString + "\n"
//                            + "Telefono: " + telefonoString + "\n"
//                            + "Correo: " + correoString+ "\n"
//                            + "Fecha de Nacimiento: " + fechaString + "\n");
        } catch (SQLException error) {
            error.printStackTrace();
        } finally {
            // LIMPIAR MEMORIA
            if (consulta != null) {
                try {
                    consulta.close();
                } catch (SQLException error) {
                    error.printStackTrace();
                }
            }
            // CERRAR CONEXION
            if (conexion != null) {
                try {
                    conexion.close();
                } catch (SQLException error) {
                    error.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_JBGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGuardar;
    private javax.swing.JTextArea JTAInfoUser;
    private javax.swing.JTextField JTContrasena;
    private javax.swing.JTextField JTCorreo;
    private javax.swing.JTextField JTFechaNacimiento;
    private javax.swing.JTextField JTNombre;
    private javax.swing.JTextField JTTelefono;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
